// UI string table for EN / BM / ZH. English is the guaranteed demo path.
export const STRINGS = {
  en: {
    appName: "Quick Mode",
    myBalance: "My Balance",
    lastUpdated: "Last updated",
    voiceMode: "VOICE MODE",
    help: "HELP",
    pay: "PAY",
    payHint: "Scan QR to pay at stores",
    payTitle: "Pay",
    paySub: "Fast payment like TnG eWallet",
    scanPay: "Scan & Pay",
    scanPayHint: "Use camera to scan merchant QR",
    scanNowDemo: "Scan now (demo)",
    payMerchant: "Pay Merchant",
    merchant: "Merchant",
    merchantPlaceholder: "e.g. Jaya Grocer",
    amountRm: "Amount (RM)",
    continuePay: "Continue",
    deals: "DEALS",
    dealsHint: "See promotions and offers",
    voice: "VOICE ASSIST",
    voiceHint: "Tap and speak what you need",
    helper: "CALL HELPER",
    helperHint: "Call Touch 'n Go customer support",
    family: "CALL FAMILY",
    familyHint: "Call your family member",
    quickModeBadge: "Old Folk Mode is ON",
    quickModeSub: "Safe · Simple · Secure",
    quickActions: "Quick actions",
    holdToTalk: "Hold to talk",
    releaseToSend: "Release to send",
    chatboxTitle: "Chat",
    chatboxPlaceholder: "Voice replies will appear here.",
    typeMessage: "Type a message",
    listening: "Listening…",
    speakNow: "Tap to speak",
    tapToStop: "Tap to stop",
    thinking: "Thinking…",
    pipelineVoice: "Voice Input",
    pipelineIntent: "Intent Detection",
    pipelineAction: "Action Execution",
    pipelineConfirm: "Confirmation",
    verifyTitle: "Please verify",
    verifyHint: "Place your thumb on the sensor",
    verified: "Verified!",
    paymentSuccess: "Payment Successful",
    topupSuccess: "Top Up Successful",
    showAtShop: "Show this at shop",
    save: "Save",
    done: "Done",
    back: "Back",
    home: "Home",
    callingTng: "Calling Touch 'n Go Helper",
    tngNumber: "1-300-88-0000",
    callFamily: "Calling Family",
    yourSon: "Ah Boy (Son)",
    promotionsTitle: "Today's Deals",
    safeNote: "Safe to view — no auto-payment",
    typedFallback: "Or type your command:",
    send: "Send",
    micDenied: "Microphone access denied.",
    micDeniedHint: "Click the lock icon in the address bar, allow Microphone, then refresh.",
    micInsecure: "Voice needs a secure connection.",
    micInsecureHint: "Open this page on the same computer at http://localhost:5173 (the network IP blocks the microphone).",
    micNoDevice: "No microphone was found on this device.",
    micBusy: "Your microphone is in use by another app.",
    micFailed: "Could not start the microphone.",
    micRetry: "Try mic again",
    tapToTalk: "Tap to talk",
    examples: "Try saying:",
    example1: "What is my balance?",
    example2: "Pay RM50 to merchant",
    example3: "Top up RM100",
    confirmCancel: "Cancel",
    confirmApprove: "Approve",
    qrInstruction: "Show this QR code to the merchant",
  },
  bm: {
    appName: "Mod Pantas",
    myBalance: "Baki Saya",
    lastUpdated: "Dikemaskini",
    voiceMode: "MOD SUARA",
    help: "BANTUAN",
    pay: "BAYAR",
    payHint: "Imbas QR untuk bayar",
    payTitle: "Bayar",
    paySub: "Pembayaran pantas seperti TnG eWallet",
    scanPay: "Imbas & Bayar",
    scanPayHint: "Guna kamera untuk imbas QR peniaga",
    scanNowDemo: "Imbas sekarang (demo)",
    payMerchant: "Bayar Peniaga",
    merchant: "Peniaga",
    merchantPlaceholder: "contoh: Jaya Grocer",
    amountRm: "Jumlah (RM)",
    continuePay: "Teruskan",
    deals: "TAWARAN",
    dealsHint: "Lihat promosi dan tawaran",
    voice: "ASISTEN SUARA",
    voiceHint: "Ketik dan cakap apa anda mahu",
    helper: "PEMBANTU",
    helperHint: "Hubungi sokongan Touch 'n Go",
    family: "KELUARGA",
    familyHint: "Hubungi ahli keluarga anda",
    quickModeBadge: "Mod Warga Emas Aktif",
    quickModeSub: "Selamat · Mudah · Selamat",
    quickActions: "Tindakan pantas",
    holdToTalk: "Tekan & tahan untuk bercakap",
    releaseToSend: "Lepas untuk hantar",
    chatboxTitle: "Chat",
    chatboxPlaceholder: "Balasan suara akan dipaparkan di sini.",
    typeMessage: "Taip mesej",
    listening: "Mendengar…",
    speakNow: "Ketik untuk bercakap",
    tapToStop: "Ketik untuk berhenti",
    thinking: "Memproses…",
    pipelineVoice: "Input Suara",
    pipelineIntent: "Pengesanan Niat",
    pipelineAction: "Pelaksanaan Tindakan",
    pipelineConfirm: "Pengesahan",
    verifyTitle: "Sila sahkan",
    verifyHint: "Letak ibu jari pada sensor",
    verified: "Disahkan!",
    paymentSuccess: "Pembayaran Berjaya",
    topupSuccess: "Tambah Nilai Berjaya",
    showAtShop: "Tunjuk di kedai",
    save: "Jimat",
    done: "Selesai",
    back: "Kembali",
    home: "Utama",
    callingTng: "Memanggil Pembantu TnG",
    tngNumber: "1-300-88-0000",
    callFamily: "Memanggil Keluarga",
    yourSon: "Ah Boy (Anak)",
    promotionsTitle: "Tawaran Hari Ini",
    safeNote: "Selamat dilihat — tiada bayaran automatik",
    typedFallback: "Atau taip arahan anda:",
    send: "Hantar",
    micDenied: "Akses mikrofon dinafikan.",
    micDeniedHint: "Klik ikon kunci pada bar alamat, benarkan Mikrofon, dan muat semula.",
    micInsecure: "Suara perlukan sambungan selamat.",
    micInsecureHint: "Buka halaman ini di komputer yang sama di http://localhost:5173.",
    micNoDevice: "Tiada mikrofon dijumpai pada peranti ini.",
    micBusy: "Mikrofon sedang digunakan oleh aplikasi lain.",
    micFailed: "Tidak dapat memulakan mikrofon.",
    micRetry: "Cuba mikrofon lagi",
    tapToTalk: "Ketik untuk bercakap",
    examples: "Cuba sebut:",
    example1: "Berapa baki saya?",
    example2: "Saya nak bayar RM50",
    example3: "Tambah RM100",
    confirmCancel: "Batal",
    confirmApprove: "Sahkan",
    qrInstruction: "Tunjuk kod QR ini kepada peniaga",
  },
  zh: {
    appName: "快捷模式",
    myBalance: "我的余额",
    lastUpdated: "更新时间",
    voiceMode: "语音模式",
    help: "帮助",
    pay: "付款",
    payHint: "扫描二维码付款",
    payTitle: "付款",
    paySub: "像 TnG eWallet 一样快速付款",
    scanPay: "扫码付款",
    scanPayHint: "使用相机扫描商家二维码",
    scanNowDemo: "立即扫码（演示）",
    payMerchant: "向商家付款",
    merchant: "商家",
    merchantPlaceholder: "例如：Jaya Grocer",
    amountRm: "金额（RM）",
    continuePay: "继续",
    deals: "优惠",
    dealsHint: "查看促销和优惠",
    voice: "语音助手",
    voiceHint: "点击并说出您的需求",
    helper: "联系客服",
    helperHint: "致电 Touch 'n Go 客服",
    family: "联系家人",
    familyHint: "拨打家人电话",
    quickModeBadge: "长者模式已开启",
    quickModeSub: "安全 · 简单 · 可靠",
    quickActions: "快捷操作",
    holdToTalk: "按住说话",
    releaseToSend: "松开发送",
    chatboxTitle: "聊天",
    chatboxPlaceholder: "语音回复会显示在这里。",
    typeMessage: "输入消息",
    listening: "正在聆听…",
    speakNow: "点击说话",
    tapToStop: "点击停止",
    thinking: "处理中…",
    pipelineVoice: "语音输入",
    pipelineIntent: "意图识别",
    pipelineAction: "执行操作",
    pipelineConfirm: "确认完成",
    verifyTitle: "请验证身份",
    verifyHint: "请将拇指放在传感器上",
    verified: "已验证！",
    paymentSuccess: "付款成功",
    topupSuccess: "充值成功",
    showAtShop: "向店家出示",
    save: "节省",
    done: "完成",
    back: "返回",
    home: "首页",
    callingTng: "正在呼叫 TnG 客服",
    tngNumber: "1-300-88-0000",
    callFamily: "正在呼叫家人",
    yourSon: "阿伟（儿子）",
    promotionsTitle: "今日优惠",
    safeNote: "仅供查看 — 不会自动付款",
    typedFallback: "或输入指令：",
    send: "发送",
    micDenied: "麦克风权限被拒绝。",
    micDeniedHint: "请点击地址栏的锁形图标，允许麦克风权限，然后刷新页面。",
    micInsecure: "语音需要安全连接。",
    micInsecureHint: "请在同一台电脑上打开 http://localhost:5173 。",
    micNoDevice: "未检测到麦克风设备。",
    micBusy: "麦克风正被其他应用占用。",
    micFailed: "无法启动麦克风。",
    micRetry: "重试麦克风",
    tapToTalk: "点击说话",
    examples: "试试说：",
    example1: "我的余额是多少？",
    example2: "付50令吉给商家",
    example3: "充值100令吉",
    confirmCancel: "取消",
    confirmApprove: "确认",
    qrInstruction: "请向商家出示此二维码",
  },
};

export function t(lang, key) {
  const table = STRINGS[lang] || STRINGS.en;
  return table[key] ?? STRINGS.en[key] ?? key;
}
